name: CI

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
        default: 'default_value1'
      param2:
        description: 'Parameter 2'
        required: true
        default: 'default_value2'
      param3:
        description: 'Parameter 3'
        required: true
        default: 'default_value3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "Param1: ${{ github.event.inputs.param1 }}"
          echo "Param2: ${{ github.event.inputs.param2 }}"
          echo "Param3: ${{ github.event.inputs.param3 }}"
